[build-system]
requires = ["setuptools", "wheel", "cmake"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3*"
skip = "*-win32 *-musllinux_i686 *-manylinux_i686"
test-skip = "*_arm64 *-musllinux_x86_64 cp310-*"
test-command = "python -c \"from jkq import ddsim\""
test-requires = ["qiskit-terra", "numpy>=1.19,<1.21", "pandas>=1.1.4", "networkx>=2.5", "quimb>=1.3", "sparse>=0.13", "cotengra @ https://github.com/jcmgray/cotengra/archive/refs/heads/master.zip"]
environment = { DEPLOY = "ON" }
build-verbosity = 3

[tool.cibuildwheel.linux]

[tool.cibuildwheel.macos]
archs = "x86_64"
environment = { MACOSX_DEPLOYMENT_TARGET = "10.15", DEPLOY = "ON" }
before-build = "brew install libomp"

[tool.cibuildwheel.windows]
