name: Deploy to PyPI

on:
  release:
    types: [ published ]
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  LIBOMP_VERSION_TAG: libomp-13.0.1
  LIBOMP_HASH:        ad8604a13319a9959ce6a4adc769b114a78d7c2cb81e08116e499310d1ba518e

jobs:
  test_bindings:
    name:    Test Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.9'
      - name: Install package
        run:  |
              pip install -U pip setuptools wheel
              pip install .
      - name: Test package
        run: |
          pip install pytest
          pip install -r requirements-test.txt
          pytest test/python

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -q build
      - name: Build sdist
        run: python -m build --sdist
      - name: Install sdist
        run: pip install --verbose dist/*.tar.gz
        env:
          CC: "gcc-10"
          CXX: "g++-10"
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [ test_bindings, build_sdist ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_macos_m1_wheels:
    name:    Build wheels on macOS for Apple Silicon
    needs: [ test_bindings, build_sdist ]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.9'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ARCHS_MACOS:        arm64
          CIBW_BEFORE_BUILD_MACOS: |
                                   curl -L -H "Authorization: Bearer QQ==" -o ${{ env.LIBOMP_VERSION_TAG }}.big_sur.bottle.tar.gz https://ghcr.io/v2/homebrew/core/libomp/blobs/sha256:${{ env.LIBOMP_HASH }} 
                                   brew install -f ${{ env.LIBOMP_VERSION_TAG }}.big_sur.bottle.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    name:    Upload dists to PyPi
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest
    if:      github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
