name: continuous integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure CMake
        shell: bash
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBOOST_ROOT=${BOOST_ROOT_1_72_0}
      - name: Build
        shell: bash
        run: cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE
      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install boost dependency
        run:  brew install boost
      - name: Install OpenMP dependency
        run:  brew install clang-omp
      - name: Configure CMake
        run:  cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        run:  cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE
      - name:              Test
        working-directory: ${{github.workspace}}/build
        shell:             bash
        run:               ctest -C $BUILD_TYPE

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Boost
        id:   cache-boost
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/boost_1_70_0
          key:  ${{ runner.OS }}-boost

      - name: Download boost
        if:   steps.cache-boost.outputs.cache-hit != 'true'
        shell: cmd
        run:  |
              C:\msys64\usr\bin\wget.exe https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.7z --no-check-certificate

      - uses: ilammy/msvc-dev-cmd@v1

      - name:  Building boost
        if:    steps.cache-boost.outputs.cache-hit != 'true'
        shell: bash
        run:   |
               "/c/Program Files/7-Zip/7z.exe" x boost_1_70_0.7z "-o${{github.workspace}}"
               cd boost_1_70_0
               ./bootstrap.bat
               ./b2.exe -j8 address-model=64 link=static threading=multi runtime-link=shared variant=release --build-type=minimal --with-program_options

      - name: Configure CMake
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -T "ClangCl" -DBoost_USE_STATIC_LIBS=ON -DBoost_USE_MULTITHREADED=ON -DBoost_USE_STATIC_RUNTIME=OFF -DBOOST_ROOT="${{github.workspace}}\boost_1_70_0" -DBOOST_INCLUDEDIR="${{github.workspace}}\boost_1_70_0\include" -DBOOST_LIBRARYDIR="${{github.workspace}}\boost_1_70_0\lib"

      - name: Build
        run: cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C $BUILD_TYPE

  coverage:
    name: Coverage
    needs: [ build-ubuntu, build-macos ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure CMake
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=1 -DBINDINGS=ON
      - name: Build
        run: cmake --build "${{github.workspace}}/build" --config Debug
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Debug
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source:             'apps include src test'
          extensions:         'h,hpp,c,cpp'
          clangFormatVersion: 12
