name: cpp-linter

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install OpenCV
        run: |
          sudo apt-get --quiet update
          sudo apt-get install --no-install-recommends libopencv-dev
      - name: Generate compilation database
        run: CC=clang-14 CXX=clang++-14 cmake -S . -B build -DBUILD_TYPE=Debug -DBINDINGS=ON -DBUILD_DDSIM_TESTS=ON
      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ""
          tidy-checks: ""
          version: "14"
          thread-comments: true
          step-summary: true
          database: "build"
          extra-args: -std=c++17
          files-changed-only: true
      - name: Fail if linter found errors
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Linter found errors" && exit 1
